### ISSUE TITLE
[🐛 BUG] - Station ID 109 (fresh pond rd) errors out

### ISSUE THREAD

**Issue by GLeaden** [Elaniobro/MMM-nyc-transit#10]
**Describe the bug**
When I add station 109 to the station list, or have it stand alone. I receive the error below.

**To Reproduce**
1. Add station 109 to your stations list in the config.js
2. Run magic mirror
3. See error

**Expected behavior**
Information about the M train leaving fresh pond road scrolling across my screen.

** Actual behavior**
Nothing.

```
(node:22291) UnhandledPromiseRejectionWarning: Error: TypeError: Cannot read property 'name' of undefined
    at client.departures.then.catch.err (/home/pi/MagicMirror/modules/MMM-nyc-transit/node_helper.js:85:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Screenshots**

**Platform (please complete the following information):**
 - Node Version:
 - Web Browser/Electron version:
 - Hardware [Raspberry Pi 3]:

**Configuration**
What does the used config.js file look like? Don't forget to remove any sensitive information!

```
 modules: [
                {
                        module: 'MMM-nyc-transit',
                        position: "top_bar",
                        header: "Next Fresh Pond Train",
                        config: {
                                        apiKey: 'MY API KEY',
                                        mtaType: 'train',
                                        stations: [237,238,109],
                                        updateInterval: 120000,
                                        walkingTime: 4,
                                }
                },

```

**Comment by GLeaden** [comment]
Whoops. I guess MTA wasn't running the M last night. My bad. :)

**Comment by Elaniobro** [comment]
@GLeaden interesting, thank you for pointing that out, it might be worth investigating, I do believe there is a `key:value` pair for `delayed` and or `out of service` I would have to dig into it, but it would most certainly, from a UI/UX perspective be valuable. 

Would you mind opening a feature request issue and outline what you think should/would be an appropriate way to handle such?

Thanks!
