### ISSUE TITLE
[🐛 BUG] - W Line (Yellow Icon)

### ISSUE THREAD

**Issue by jon7187** [Elaniobro/MMM-nyc-transit#18]
**Describe the bug**
W lines do not have the yellow color

**To Reproduce**
1. Add station 3, see W line

**Expected behavior**
W with a yellow circle

** Actual behavior**
W without a yellow circle

**Additional context**
NBD, figured minor tweak in the main file ... BTW your module is what I have been dreaming of forever!

**Comment by Elaniobro** [comment]
Nice catch @jon7187! This was resolved.
