### ISSUE TITLE
[💡 FEATURE REQUEST] Leave @: 8:28am, 8:33am, 8:40am

### ISSUE THREAD

**Issue by jon7187** [Elaniobro/MMM-nyc-transit#19]
**Is your feature request related to a problem? Please describe.**
Refresh time every 5 minutes isn't enough for when to leave my apartment.

**Describe the solution you'd like**
Would like to take the ((departure time) - (walking time))+(current time) so I can ignore refresh factoring into the time it will leave:
eg. N Astoria-Ditmars Blvd Leave @: 8:28am, 8:33am, 8:40am

**Describe alternatives you've considered**
I've considered adjusting with current time the values for a countdown that is more accurate to the minute, but would require too high a frequency pull. 

Could there be a way to store the values locally and using the clock to knock those values down every minute?

eg. Every 5min -> pull from MTA, Every 30 seconds -> update departure time?

**Comment by Elaniobro** [comment]
@jon7187 I am not entirely sure I am understanding your feature request. 

Would you please elaborate with more detail and or additional examples, explanations, etc..?

**Comment by jon7187** [comment]
**Current Status:**
-MTA pull @ 8am -> arrival in 11min
-User pads 5min
-Display shows 6 min
-8:04:59am display still shows 6min
-MTA pull @ 8:05am -> arrival in 1min

**Potential Fixes**
_Option One:_
Recommended Behavior:
-MTA pull @ 8am -> arrival in 11min
-User pads 5min
-Display shows 6 min
-8:01am refresh locally to display 5min 
   - (arrival (11min) - padding (5min) - elapsed time since pull (1min)) = 5 min
-8:02am refresh locally to display 4min
-8:03am refresh locally to display 3min
-8:04am refresh locally to display 2min
-MTA pull @ 8:05am -> arrival in 1min

_Option Two:_
-MTA pull @ 8am -> arrival in 11min
-User pads 5min
-Display shows 8:06am
-MTA pull @ 8:05am ->  display shows 8:06am

_Option Three:_
-MTA pull @ 8am -> arrival in 11min
-User pads 5min
-Display shows 6 min & refresh time of 8am

**Comment by Elaniobro** [comment]
@jon7187 Please take a look. This enhancement was pushed out.
