### ISSUE TITLE
[💡 FEATURE REQUEST] Walk time per station

### ISSUE THREAD

**Issue by jon7187** [Elaniobro/MMM-nyc-transit#22]
**Is your feature request related to a problem? Please describe.**
Station list have different walk times which require different padding (walk time)

**Describe the solution you'd like**
[3,271] 30th Ave (NW lines) Steinway (R): 8min and 12min walk respectively. 

Having an array of padding to match the stations

```
stations: [3,271],
walkingTime: [8,12]
```

**Comment by Elaniobro** [comment]
@jon7187 Please take a look, let me know.
