### ISSUE TITLE
[💡 FEATURE REQUEST] Uptown/Downtown Only

### ISSUE THREAD

**Issue by jon7187** [Elaniobro/MMM-nyc-transit#23]
**Is your feature request related to a problem? Please describe.**
Feed is crowded with trains that terminate one stop away from me. Would only want to show arrival times for the ones going into Manhattan.

**Describe the solution you'd like**
A config class as an array to match to stations for uptown/downtown/both [0,1,2] or east/west/both [0,1,2]

e.g. 30th Ave & Steinway, _only Eastbound trains_
      stations: [3,271],
      directions: [0,0]

e.g. 30th Ave & Steinway, _only Downtown trains_
      stations: [3,271],
      directions: [1,1]

e.g. 30th Ave & Steinway, _all directions_
      stations: [3,271],
      directions: [2,2]

**Comment by Elaniobro** [comment]
@jon7187 Please take a look, let me know.
