### ISSUE TITLE
Module will not load.

### ISSUE THREAD

**Issue by shortbkfilm** [Elaniobro/MMM-nyc-transit#24]
The module will only load the header and nothing else. I tried to follow another thread on a similar issues but did not find a resolution. Code is below.

{
module: "MMM-nyc-transit",
position: "top_left",
header: "Next Train",
config: {
apiKey: "apikey...",
displayType: "list",
mtaType: "train",
stations: [259],
updateInterval: 300000,
walkingTime: 10,
},
},

Any help would be appreciated.

**Comment by Elaniobro** [comment]
@shortbkfilm; what version of this module are you using? Can you please copy/paste the `package.json` file you are using?

Also, it can take a few minutes for the module to display results sometimes. I believe this is an issue on the MTA API's side.

**Comment by shortbkfilm** [comment]
Using  version 2.9.0.  

Have run the module for up to half hour with nothing loading. 
{
  "name": "magicmirror",
  "version": "2.9.0",
  "description": "The open source modular smart mirror platform.",
  "main": "js/electron.js",
  "scripts": {
    "start": "sh run-start.sh",
    "install": "cd vendor && npm install",
    "install-fonts": "cd fonts && npm install",
    "postinstall": "sh untrack-css.sh && sh installers/postinstall/postinstall.sh && npm run install-fonts",
    "test": "NODE_ENV=test ./node_modules/mocha/bin/mocha tests --recursive",
    "test:unit": "NODE_ENV=test ./node_modules/mocha/bin/mocha tests/unit --recursive",
    "test:e2e": "NODE_ENV=test ./node_modules/mocha/bin/mocha tests/e2e --recursive",
    "config:check": "node tests/configs/check_config.js",
    "lint": "grunt"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/MichMich/MagicMirror.git"
  },
  "keywords": [
    "magic mirror",
    "smart mirror",
    "mirror UI",
    "modular"
  ],
  "author": "Michael Teeuw",
  "contributors": [
    "https://github.com/MichMich/MagicMirror/graphs/contributors"
  ],
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/MichMich/MagicMirror/issues"
  },
  "homepage": "https://magicmirror.builders",
  "devDependencies": {
    "chai": "^4.1.2",
    "chai-as-promised": "^7.1.1",
    "current-week-number": "^1.0.7",
    "danger": "^3.1.3",
    "grunt": "latest",
    "grunt-eslint": "latest",
    "grunt-jsonlint": "latest",
    "grunt-markdownlint": "latest",
    "grunt-stylelint": "latest",
    "grunt-yamllint": "latest",
    "http-auth": "^3.2.3",
    "jsdom": "^11.6.2",
    "jshint": "^2.10.2",
    "mocha": "^4.1.0",
    "mocha-each": "^1.1.0",
    "mocha-logger": "^1.0.6",
    "spectron": "^3.8.0",
    "stylelint": "latest",
    "stylelint-config-standard": "latest",
    "time-grunt": "latest"
  },
  "dependencies": {
    "colors": "^1.1.2",
    "electron": "^3.0.13",
    "express": "^4.16.2",
    "express-ipfilter": "^1.0.1",
    "feedme": "latest",
    "helmet": "^3.9.0",
    "iconv-lite": "latest",
    "lodash": "^4.17.11",
    "moment": "latest",
    "request": "^2.88.0",
    "rrule": "^2.6.2",
    "rrule-alt": "^2.2.8",
    "simple-git": "^1.85.0",
    "socket.io": "^2.1.1",
    "valid-url": "latest"
  }
}

**Comment by shortbkfilm** [comment]
Using version 2.1.3, and have let the module run for up to half hour without anything loading. 

{
  "name": "MMM-nyc-transit",
  "version": "2.1.3",
  "description": "New York City realtime transit module for magic mirror",
  "main": "MMM-nyc-transit.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "lint": "eslint **/*.js --ignore-pattern node_modules/"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/Elaniobro/MMM-nyc-transit"
  },
  "keywords": [
    "Magic",
    "Mirror",
    "Magic Mirror",
    "MMM",
    "NYC",
    "transit",
    "subway",
    "bus"
  ],
  "author": {
    "name": "Elan Trybuch",
    "email": "elan@trybuch.com",
    "url": "https://elan.trybuch.com"
  },
  "license": "MIT",
  "devDependencies": {
    "chalk": "^2.4.1",
    "eslint": "^6.0.1",
    "fs-extra": "^7.0.0",
    "husky": "^3.0.0",
    "mta-realtime-subway-departures": "0.0.13"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint"
    }
  },
  "dependencies": {
    "mta-subway-stations": "0.0.2"
  }
}

**Comment by Elaniobro** [comment]
Do you have an MTA API key?

**Comment by Elaniobro** [comment]
@shortbkfilm the module is failing for all stations, as of now. Looking in the logs I find/see the following error:
`UnhandledPromiseRejectionWarning: Error: Error: Missing at least one required field for Message .transit_realtime.FeedMessage:`

The feed itself is corrupt. Apparently this is a known issue that happens intermittently.

You may read more here: [MTA developer resources](https://groups.google.com/forum/#!topic/mtadeveloperresources/WebdjDeGJyI)

**Comment by shortbkfilm** [comment]
I do have an api key.

**Comment by shortbkfilm** [comment]
So, currently theres nothing to be done?

**Comment by Elaniobro** [comment]
Correct. If you try starting it up, you should see trains on the screen. Nothing was done by me.
