### ISSUE TITLE
[🐛 BUG] - Multiple stations with the same ID

### ISSUE THREAD

**Issue by bmtully** [Elaniobro/MMM-nyc-transit#25]
I'm unable to access times for Queensboro Plaza (station id 461), getting the error "Cannot read property 'daytimeRoutes' of undefined"

Looking at the MTA's API documentation, it seems there are 2 stations with the ID of 461, even though they're in the same place. One returns the schedule for IRT trains and the other returns the schedule for BMT trains. Perhaps the API is returning both and the script isn't able to handle/combine them?

Here are both entries from the MTA database-- note most other stations just have one.
**461,461,**718,IRT,Flushing,Queensboro Plaza,Q,7,Elevated,40.750582,-73.940202,Astoria - Flushing,Manhattan
**461,461,**R09,BMT,Astoria,Queensboro Plaza,Q,N W,Elevated,40.750582,-73.940202,Astoria - Flushing,Manhattan

Source: http://web.mta.info/developers/data/nyct/subway/Stations.csv

**Comment by Elaniobro** [comment]
@bmtully Please update the description/title with the proper information that is part of the bug report template issue you see when reporting a new issue. Thanks!

**Comment by Elaniobro** [comment]
@bmtully please update your module with `git pull` problem should be fixed now.

**Comment by george-dilthey** [comment]
@Elaniobro Not sure if I should open up another bug here, but I'm getting errors with station ID 461. Spot checking other IDs seem to be fine, but 461 in my config file outputs the below when I start Magic Mirror. If I have 2 stations and one of them is 461, neither shows up. I just get the "Next Train" header. LMK if I can help debug at all. 

`[19.02.2022 13:19.17.799] [ERROR] (node:11075) UnhandledPromiseRejectionWarning: Error: Error: invalid wire type 4 at offset 1
    at /home/pi/Development/MagicMirror/modules/MMM-nyc-transit/node_helper.js:187:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

`[19.02.2022 13:19.17.802] [ERROR] (node:11075) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)`

`[19.02.2022 13:19.17.805] [ERROR] (node:11075) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
