### ISSUE TITLE
Unable to load Module

### ISSUE THREAD

**Issue by Hram2008** [Elaniobro/MMM-nyc-transit#27]
Attempting to install the MMM-nyc-transit module with difficulty.  I see directory folder and i added to the config file but it will not run.

 {
			module: "MMM-nyc-transit",
			position: "top_bar",
			header: "Next Train",
			config: {
			  apiKey: 'I HAVE APIKEY from MTA',
			  displayType: 'marquee',
			  mtaType: 'train',
			  stations: [237,238],
			  updateInterval: 300000,
			  walkingTime: 5,
			}
		},

**Comment by Elaniobro** [comment]
Hi @Hram2008 thank you for using the module. I am happy to help, but the information you provide is not enough.

When you first created the issue,  you are given a choice:
* bug report
* feature request

With in both, is a template that asks for information. Please re-visit this template and add the requested information so I may begin to assist.

Thanks!

**Comment by Hram2008** [comment]
Hello,


I will go back and fill in the Bug report, i was not sure if this is a bug report inquiry.  Thank you for your time.

**Comment by Elaniobro** [comment]
@Hram2008 no problem, happy to help. While we wait for your update, please make sure you have installed Magic Mirror properly and that you also installed the module in the correct folder and ran the install command!

**Comment by Hram2008** [comment]
**Describe the bug**
After installing the Module and updating the config file the MMM-nyc-transit did not load on the Magic Mirror 

**To Reproduce**
Steps to reproduce the behavior: NA
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
I expected after saving and restarting the Magic Mirror application it would display NYC transit time

** Actual behavior**
All other modules will load besides the Transit tiems (i.e weather, holidays...)

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Platform (please complete the following information):**
 - Node Version:
 - Web Browser/Electron version:
     Chromium - Ver 78.0.3904.108
 - Hardware [e.g. Raspberry Pi 2/3, Windows, Mac, Linux, System V UNIX]:
      Raspberry Pi 4 B+ 4GB
 
**Configuration**
What does the used config.js file look like? Don't forget to remove any sensitive information!

/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 12,
	units: "Imperial",
	// serverOnly:  true/false/"local" ,
			     // local for armv6l processors, default 
			     //   starts serveronly and then starts chrome browser
			     // false, default for all  NON-armv6l devices
			     // true, force serveronly mode, because you want to.. no UI on this device
	
	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_right"
		},
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_right",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics",
						fade: false			}
				]
			}
		},
		/*
		{
			module: "compliments",
			position: "lower_third"
		},
		* */
		{
			module: "currentweather",
			position: "top_left",
			config: {
				location: "",
				locationID: "",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "",
				roundTemp: true
			}
		},
		{
			module: "weatherforecast",
			position: "top_left",
			header: "Weather Forecast",
			config: {
				location: "",
				locationID: "",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "",
				fade: false
				
			}
		},
		 {
			module: "MMM-nyc-transit",
			position: "top_bar",
			header: "Next Train",
			config: {
			  apiKey: '',
			  displayType: 'marquee',
			  mtaType: 'train',
			  stations: [237,238],
			  updateInterval: 300000,
			  walkingTime: 5,
			}
		},
                /*
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
	**/
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}


**Additional context**
after install the module installed the PI folder
Add any other context about the problem here.

**Comment by Hram2008** [comment]
Good Evening, 

 

I uploaded additional information.

**Comment by Elaniobro** [comment]
Can you walk me through how you installed this module?

Can you upload a screenshot of your IDE showing me the folder structure of:
* `magicMirror`
* `magicMirror/modules`
* `magicMirror/modules/MMM-nyc-transit`

Thanks!

**Comment by Hram2008** [comment]
Can you walk me through how you installed this module?
I loaded module in the Modules folder.

Can you upload a screenshot of your IDE showing me the folder structure of:

![Tree 2](https://user-images.githubusercontent.com/61397417/75246817-8e2d3c80-579e-11ea-84d5-01e631f3d4b7.JPG)
![Tree 3](https://user-images.githubusercontent.com/61397417/75246818-8e2d3c80-579e-11ea-87f7-a8e8a960f9e2.JPG)
![Tree 4](https://user-images.githubusercontent.com/61397417/75246820-8e2d3c80-579e-11ea-8117-5bb6e5202925.JPG)
![Tree](https://user-images.githubusercontent.com/61397417/75246821-8e2d3c80-579e-11ea-8dfd-1d2ecd1242b8.JPG)

**Comment by Elaniobro** [comment]
@Hram2008 the module is not installed. 

Please refer to the directions in the `README.md` but you need to make sure you ran `npm i` in the `MMM-nyc-transit` folder. I can tell you did not do this, because there isn’t a `node_modules` directory.

**Comment by Hram2008** [comment]
Thank you for your review, i will give it another look.
