### ISSUE TITLE
[🐛 BUG] - Please update README.md

### ISSUE THREAD

**Issue by teachng** [Elaniobro/MMM-nyc-transit#35]
**Issue**
Two things:
1. Update the description to the updated data feed site (Thanks Elaniobro): https://api.mta.info/
2. Endpoint/station data doesn't seem to be available. Currently, the only real-time data available are of the lines themselves and not the station. Not sure if theres something that can be done with that

**Comment by Elaniobro** [comment]
@teachng I updated the README.md to reflect the new API key requirements. As for your `2` I will need you to be more explicit. I am not understanding your question.

The module that I use, will look up the line(s) at your station ID and make the subsequent API calls for each train line and respond with an aggregated feed that I then parse through in the module.

Closing this ticket for now, but feel free to re-open and comment with more details.

p.s. Please populate the issue title and use the format to help me better understand your system to help debug :)

**Comment by Elaniobro** [comment]
@all-contributors please add  @kurtraschke for bug code

**Comment by Elaniobro** [comment]
@all-contributors please add @nipper2000h for bug
