### ISSUE TITLE
[🐛 BUG] - Please put your title here. 

### ISSUE THREAD

**Issue by teachng** [Elaniobro/MMM-nyc-transit#42]
**Describe the bug**
I put in two instances of the module onto my magic mirror, with one showing the Central Park West 86th St. station uptown and the other instance as the downtown. I respectively set the boolean values with the former being (upTown: true, downTown: false) and the latter being (upTown: false, downTown: true).

What I see on the mirror, though, is the same stops and same times for both instances. Shouldn't both instances show different trains and times?

**To Reproduce**
1. Input two modules of 'MMM-nyc-transit' onto config file
2. Set first and second module's station ID to '158'
3. Set first module upTown value to true, downTown value to false; set second module upTown value to false, downTown value to true
4. Run Magic Mirror

**Expected behavior**
Two different modules of subways transit, the first instance as uptown trains and times, the second instance as downtown trains and times

** Actual behavior**
Both instances show the same trains and times. No differences between the two

**Screenshots**
https://imgur.com/a/c7om12R - sample code & output on mirror

**Platform (please complete the following information):**
 - Node Version: latest
 - Web Browser/Electron version: latest
 - Hardware [e.g. Raspberry Pi 2/3, Windows, Mac, Linux, System V UNIX]: RPi 3B

**Configuration**
What does the used config.js file look like? Don't forget to remove any sensitive information!

**Additional context**

**Comment by Elaniobro** [comment]
@teachng please update the title of this issue properly will submitting a new issue.
`[🐛 BUG] - Please put your title here.` with replacing the `Please put your title here.` portion.

As for your issue, based on your screenshot of the code, you have two instances of the module running within your mirror. You only need one.

This is what you have:
```js
 {
    module: 'MMM-nyc-transit',
    position: "top_bar",
    header: "Next Train",
    config: {
      apiKey: 'YOUR_KEY_HERE',
      displayType: 'marquee',
      mtaType: 'train',
      stations: [
        {
          stationId: 158,           
          walkingTime: 0,
          dir: {
              upTown: true,
              downTown: false
          }
        },
      ],
      updateInterval: 300000
    }
  },
 {
    module: 'MMM-nyc-transit',
    position: "top_bar",
    header: "Next Train",
    config: {
      apiKey: 'YOUR_KEY_HERE',
      displayType: 'marquee',
      mtaType: 'train',
      stations: [
        {
          stationId: 158,           
          walkingTime: 0,
          dir: {
              upTown: false,
              downTown: true
          }
        },
      ],
      updateInterval: 300000
    }
  }
```

This is what you _**Should**_ have
```js
 {
    module: 'MMM-nyc-transit',
    position: "top_bar",
    header: "Next Train",
    config: {
      apiKey: 'YOUR_KEY_HERE',
      displayType: 'marquee',
      mtaType: 'train',
      stations: [
        {
          stationId: 158,           
          walkingTime: 0,
          dir: {
              upTown: true,
              downTown: true
          }
        },
      ],
      updateInterval: 300000
    }
  }
```

The module is not designed to have multiple instances running within the mirror, as such I will be closing this ticket out as won't fix. Please feel free to submit feature/enhancement requests and future bugs you may find. Thanks!
