### ISSUE TITLE
[Question] My Own City?

### ISSUE THREAD

**Issue by dxfan227** [Elaniobro/MMM-nyc-transit#43]
Hello! @Elaniobro 

Hope this is an okay way to get in touch. I am interested in creating my own transit module for my magic mirror, with my specific city. At first I would be happy with simply the next time the bus is going to show up/how late it might be in either direction.

Building upon that would be a small map with a moving real time bus to see where it is at on the map.

My city offers a GTFS zip file for transit, but I am not sure if it offers real time data. I do notice my Lyft App and Transit App on iPhone do show busses in real time so I am hopefull it exists.

I understand its a huge undertaking, and by no means to expect anyone to walk me through every single step of this ( unless they want to be awesome!) but what would a good place be to start? I have no experience! I am technical enough to get in trouble ( magic mirror set up, modules installed, some minor configuration modification etc) but no formal background in python/javascript...etc.

Thank you for any help you can provide on this

**Comment by Elaniobro** [comment]
Hi @dxfan227; this is a most unusual way, but its fine. 

I think your first start is to look into https://github.com/protobufjs/protobuf.js/wiki which will help you read the real time feed and convert it to json so you can do your thang!
