### ISSUE TITLE
[🐛 BUG] - All SIR trains not showing up

### ISSUE THREAD

**Issue by zekromy123456789** [Elaniobro/MMM-nyc-transit#46]
when I plug in any station for the SIR nothing pops up within the module however all other trains (tested nearly all the lines) work with no problem in both directions.

**Comment by Elaniobro** [comment]
Hi @zekromy123456789 thanks for the feedback and posting the bug. I tracked down the issue to missing station IDs for the destination. I submitted a PR to the module to fix this issue. @ericandrewlewis and I will work to resolve it shortly! 

Keep an eye on this issue to know when the bug has been squashed and please let me know if you come across any other issues! 

Happy holidays 🎅

**Comment by zekromy123456789** [comment]
Thank u guys so much for all the work u put into ur code really helps a lot of people like me who are trying to assemble a project with little coding experience. Very grateful! Hope u have a happy holidays as well.🎄

**Comment by Elaniobro** [comment]
@zekromy123456789  I pushed ahead and updated the module. Keep an eye out for a new patch bump, that will be using the npm registry fix vs the hard coded github fix I have now. Sorry for the wait as well as the duplicate PR's, I had inadvertently used my wrong github acct so I closed and re-worked it with this one :) 

I am closing this issue for now, and as always, please open a new issues to report any bugs/ideas/etc.. you find and thank you for your feedback!

**Comment by ericandrewlewis** [comment]
1.1.1 has been published to npm. I'm sorry about the delay, GMail sends my Github notifications to the Trash for reasons I'm still trying to figure out. 🔥💻

**Comment by Elaniobro** [comment]
@zekromy123456789; I updated the module with the dynamic semVer version of the pkg. Please update your mirror module :)
