### ISSUE TITLE
Needs list version

### ISSUE THREAD

**Issue by Kendiggity973** [Elaniobro/MMM-nyc-transit#8]
I’m thinking a list version would make this better. Such as

L Train Halsey stop: Arrives in 5 minutes
M train: Arrives in 12 minutes

With a countdown possibly color coded for time remaining based on walk time.

My mirror will be pulling a lot of stations data and I feel like a ticker would be inconvenient as a form of display

**Comment by Elaniobro** [comment]
This issue is now a duplicate of #9 and will be tracked there.
