### ISSUE TITLE
[💡 FEATURE REQUEST] - Add list option

### ISSUE THREAD

**Issue by Kendiggity973** [Elaniobro/MMM-nyc-transit#9]
Can we change the output text of certain things. A.k.A instead of it saying 16th /8th can we have it set up to say Manhattan bound, Or Brooklyn Bound. Or north/south east/west. i Feel like that would be much more appealing to the eyes for people who dont want to see the same train mutliple times.

**Comment by Elaniobro** [comment]
@Kendiggity973 which station ID are you using for

>16th /8th

Per your suggestion/reasoning:

>i Feel like that would be much more appealing to the eyes for people who dont want to see the same train mutliple times.

Wouldn't this idea be the same thing as what is currently happening but with up/downdtown? e.g. 
<img src="https://emojis.slackmojis.com/emojis/images/1471450078/1024/6train.png?1471450078" width="16"/> downtown 6min | <img src="https://emojis.slackmojis.com/emojis/images/1471450078/1024/6train.png?1471450078" width="16"/> downtown 10min | <img src="https://emojis.slackmojis.com/emojis/images/1471450078/1024/6train.png?1471450078" width="16"/> downtown 15min | <img src="https://emojis.slackmojis.com/emojis/images/1471450078/1024/6train.png?1471450078" width="16"/> uptown 5min | <img src="https://emojis.slackmojis.com/emojis/images/1471450078/1024/6train.png?1471450078" width="16"/> uptown 10min

If its not, please ammend your original issue to suss out the remaining questions from the template, so I may better begin to understand your request:

>**Describe the solution you'd like**
>A clear and concise description of what you want to happen.

>**Describe alternatives you've considered**
>A clear and concise description of any alternative solutions or features you've considered.

(FWIW, templates are there for you to fill out, not replace e.g. use it as a form. It helps keeps issues organized and understandable for all users. 👍 )

**Comment by Kendiggity973** [comment]
its not though not for what i'm doing. When i put in id 129 It spits out L | Franklin Av 6 min L | Franklin Av | 9 min L | Franklin Av 29 min   L | 14 st / 6 av 3 min L | 14 st / 6 av 
when i use ID 110 it says  M | 75th 3 min M | 75th 6 min

what makes more sense and Tying into my other suggestion as well is

L | To Brooklyn | 3 min | 6 min | 26 min 
L | To Manhattan | 7 min |  14 min | 25 min
M | To Brooklyn | 3 min | 6 min | 26min
M | To Manhattan | 7 min | 14 min | 26 min

maybe make the time color coded (e.g.) under 10 min = red | under 15 = yellow | 20 or more min

**Comment by Elaniobro** [comment]
Ahh, ok, this makes way more sense to me know. I can also see how this would only really be viable in a list format, as you have done so. The scrolling marquee will be kept as is, but I will begin looking into this for a list option configuration.

**Comment by Elaniobro** [comment]
@Kendiggity973 please go ahead and update your mirror, I added a list option  👍
